### ISSUE TITLE
New Location Permissions Scheme for Android Q 

### ISSUE THREAD

**Issue by christocracy** [nishkarsh/android-permissions#13]
As you're probably aware, there's a [new location permissions model for Android Q](https://developer.android.com/preview/privacy/device-location).

I've donated to you in the past.  How much would you like for a donation to upgrade this library to support the new *location permissions* of Android Q?

**Comment by nishkarsh** [comment]
Hey @christocracy!
I have not spent enough time on android recently but this should mostly affect the permission that is required for using location in the background and not the way it is asked. I think you should be able to handle the behavior by just asking for permission through the same available methods.

I will spend some time to understand it a little more and see if any changes are needed in the way the permission needs to be asked.

Sorry for the delayed response, I was out of town!
Btw, thanks for raising this!

**Comment by christocracy** [comment]
Thanks!

**Comment by nishkarsh** [comment]
Hey @christocracy! I verified the behavior and the library seems to be working as I was expecting. With the change that Android has brought with API 29 (Q) with respect to the app working with location while being in the background, the only thing that changes is the addition of permission **ACCESS_BACKGROUND_LOCATION** in the list of permissions being requested. Everything else is just handled by Android. Since the newer version of android-permissions also allows the developers to check if a rationale should be shown, the showing of the reason for accessing the location in the background could be handled as well.

If there is something unexpected or if you are looking for some specific behavior, let me know and I would be happy to help extend the library to support that!

**Comment by christocracy** [comment]
Thanks for you support.  I've sent you $100 USD via PayPal.

**Comment by nishkarsh** [comment]
Thanks Chris! I appreciate your help in return to support this library.
