### ISSUE TITLE
Project should be moved off jcenter repository 

### ISSUE THREAD

**Issue by mikejeep** [nishkarsh/android-permissions#20]
The JCenter repository is shutting down and Android Studio now displays a warning when including dependencies that access it. It appears that android-permissions is hosted on JCenter and will need to be moved to allow future updates and prevent this warning.

From https://developer.android.com/studio/build/jcenter-migration:

"JFrog, the company that maintains the JCenter artifact repository used by many Android projects, made JCenter a read-only repository on March 31st, 2021. According to the announcement, JCenter will allow downloads of existing artifacts indefinitely.

Developers who publish artifacts on JCenter should migrate their packages to a new host, such as Maven Central.

Developers who use dependencies from JCenter will need to find the new location of updated versions of those dependencies."

**Comment by nishkarsh** [comment]
Hey @mikejeep! Thanks for brining this to my knowledge, I will move it off to Maven Central as soon as possible.

**Comment by christocracy** [comment]
Hi @nishkarsh.  I don't see this on maven-central yet.

**Comment by nishkarsh** [comment]
Hey @christocracy, @mikejeep, sorry for this getting delayed. I am most probably going to take out time today and tomorrow to push this to maven-central.

**Comment by christocracy** [comment]
@nishkarsh Thanks for the quick update.

I'm currently using `0.1.8`.  Could you please ensure that older version gets migrated to `mavenCentral` as well?

**Comment by christocracy** [comment]
@nishkarsh I've sent you $300 USD for your support.

![](https://dl.dropbox.com/s/dcg4qj6jskqxtjj/Screen%20Shot%202021-07-20%20at%2011.43.57%20AM.png?dl=1)

**Comment by nishkarsh** [comment]
Thanks for the contribution @christocracy, I appreciate it.

I have started the process of migration of older archives to Maven Central. Unfortunately moving to `sonatype` requires me to verify the ownership of the domain that I don't own anymore (intentfilter.com) and that's why going forward the group name under which the artifacts would be released is: `io.github.nishkarsh`. 

The process of moving the older versions is also troublesome at the moment since publishing an artifact to Maven Central has to meet certain requirements for which the older builds have to be republished. Configuring Travis CI is going to take some time after which the publishing should become easy again but for now, I have published `io.github.nishkarsh:android-permissions:1.0.9` manually which is the same as old `com.intentfilter:android-permissions:1.0.9` that could be found at `mavenCentral()`.

Please let me know if you find trouble configuring the dependency.

Over the next few days, the other older versions would be moved to Maven Central too and I will close the issue post that. Thanks!

**Comment by mikejeep** [comment]
Thanks @nishkarsh! But I am a little confused -- the current version on JCenter is 2.0.54, and I don't see version 1.0.9 listed on GitHub?

**Comment by nishkarsh** [comment]
Hey @mikejeep! I am sorry for creating the confusion. In summary, the builds from `0.1.7` to `2.0.54` are now available at `mavenCentral()`. The version `1.0.9` is indeed not listed on github under releases. The version got mistakenly published now and contains no new functionality or bugfix.

All the published versions would soon appear at https://search.maven.org/artifact/io.github.nishkarsh/android-permissions
The remaining older versions would also be published soon.

**Comment by christocracy** [comment]
Thanks very much @nishkarsh.  Seems to work for me now.

**Comment by mikejeep** [comment]
Thank you @nishkarsh ! Worked for me as well. Going to send another contribution for your efforts, I appreciate it.

**Comment by aricab** [comment]
Hi nishkarsh, 
I'm trying to remove jcenter() since it was failing lately (timed out).

When building my project it keeps saying: **"Could not find com.intentfilter:android-permissions:0.1.7"**
I've added maven { url "https://repo1.maven.org/maven2/" } in android/build.gradle and I see that now is seraching in the locations: 
- https://repo1.maven.org/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
- https://repo1.maven.org/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.jar

should I redirect somehow to https://repo1.maven.org/maven2/io/github/nishkarsh/android-permissions/0.1.7/android-permissions-0.1.7.aar ?

Adding **implementation 'io.github.nishkarsh:android-permissions:0.1.7'** didn't help ..

I'll apreciate any help
Thanks!

**Comment by aricab** [comment]
> Hi nishkarsh, I'm trying to remove jcenter() since it was failing lately (timed out).
> 
> When building my project it keeps saying: **"Could not find com.intentfilter:android-permissions:0.1.7"** I've added maven { url "https://repo1.maven.org/maven2/" } in android/build.gradle and I see that now is seraching in the locations:
> 
> * https://repo1.maven.org/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
> * https://repo1.maven.org/maven2/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.jar
> 
> should I redirect somehow to https://repo1.maven.org/maven2/io/github/nishkarsh/android-permissions/0.1.7/android-permissions-0.1.7.aar ?
> 
> Adding **implementation 'io.github.nishkarsh:android-permissions:0.1.7'** didn't help ..
> 
> I'll apreciate any help Thanks!

I think I was able to FIX it, **changing the android-permission dependency**. 
Thanks @christocracy as your post was the one that helped me: https://github.com/transistorsoft/flutter_background_geolocation/issues/605

It always happens to me, I struggle with something for days, and when I finally decide to write a question, I find a solution immediately after. My conclusion is that I should not take long to ask to have the answer before. =)

THANKS.

**Comment by mikejeep** [comment]
> When building my project it keeps saying: **"Could not find com.intentfilter:android-permissions:0.1.7"**

FYI you are using an older version; for the benefit of others who may find this issue later, this would be the most current line for your project's build.gradle:

`implementation 'io.github.nishkarsh:android-permissions:2.0.54'`

**Comment by vish2595** [comment]
@nishkarsh I am getting read only repo access.
