### ISSUE TITLE
Looks like the library was abandoned by the creator. Don't use that!!!  

### ISSUE THREAD

**Issue by mariopce** [nishkarsh/android-permissions#26]

**Comment by mariopce** [comment]
Issue fixed the latest build updated. Thank you

**Comment by christocracy** [comment]
>Looks like the library was abandoned by the creator. Don't use that!!

I suggest you edit the *hysterical*  title of this issue.  I've been using this library for over 3 years and @nishkarsh has been incredibly responsive to all my issues.

**Comment by nishkarsh** [comment]
Hey folks! I thought I would just pitch in to resolve this. 

@mariopce thanks for creating this issue to create a sense of urgency to fix the original issue, though it could have been done by following up again on the original thread for the issue created. I still appreciate that you notified about the issue and you should absolutely continue to do so.

@christocracy I appreciate you participating in this thread and I think if we have to talk about the original issue here, that would be missing guidelines for contribution by others. I should probably mention some of the guidelines so that it's easier for other folks to contribute in a better way, including proper description and tests for any changes made.

Ultimately, I believe that any open source library/project would continue to exist only if the community contributes by raising issues, suggesting features and contributing actual code.

Thanks once again!

**Comment by mariopce** [comment]
Thank You @nishkarsh for your work. I'm grateful. Hope U are well
