### ISSUE TITLE
Using checkPermissions() prompts for first request, but not subsequent requests received while waiting for user

### ISSUE THREAD

**Issue by mikejeep** [nishkarsh/android-permissions#4]
Using `checkPermissions()`, if there is a pending prompt for one permission, and request(s) for other permission(s) arrive, the user is never prompted for the additional permission(s) until the app restarts. Looking at logcat output, it appears that the library believes there is still a pending request for the second permission but that prompt is never shown to the user.

For example, upon launching my app, it asks for `ACCESS_COARSE_LOCATION` almost immediately. Within a short period of time (less than a second), `READ_PHONE_STATE` typically becomes needed by another method. In this instance, `ACCESS_FINE_LOCATION` was also requested. The user gets the location permission prompt, but the phone permission prompt never appears unless you shut down and restart the app. Logcat output attached with comments:

[logcat.txt](https://github.com/nishkarsh/android-permissions/files/1464152/logcat.txt)

**Comment by nishkarsh** [comment]
The scenario where a permission dialog is being shown and another permission is asked later is explicitly handled by the library and another permission dialog gets stacked up for the latter permission. However, in specific cases where the shown dialogs do not get user input and are leaked due to their parent context getting destroyed (in case the hosting Activity gets destroyed), the library does not recognize and hence it believes the permissions are still pending.

While this can be handled if the lifecycle is being handled properly in the app using the library, it makes sense for the library to also have the capability to know about the dialogs not being shown anymore. I will see how difficult that is and will update on if it can be handled.

Thanks for reporting the behavior!

**Comment by mikejeep** [comment]
I actually may have found the cause of the issue. In my app's manifest, I used `launchMode=singleInstance`. When changing that to any other option, the permission prompts from your library appear to stack properly. I need to do more testing to determine if that otherwise negatively impacts my app, but that appears to be a caveat you may want to document for other users.

**Comment by nishkarsh** [comment]
@mikejeep Thanks for spending time on this and figuring the out the cause. This is a good finding.
I tried reproducing it on a minimal app and was able to reproduce the issue.

Because of this, I finally found that an intent flag FLAG_ACTIVITY_NEW_TASK was not paired with FLAG_ACTIVITY_MULTIPLE_TASK which should have been there to create multiple tasks for 


I will spend
The good thing is that now that we know the cause, we should be ab

**Comment by nishkarsh** [comment]
@mikejeep Thanks for spending time on this and figuring out the cause. This is a good finding. 
I tried this on a minimal app and was able to reproduce the issue. 

I am not sure why `launchMode=singleInstance` will cause this but on doing a bit of research I realized that it should have never worked for showing multiple permission dialogs stacked up (even without the launchMode). The permission dialog is supposed to be shown in a new task but how to show another dialog if another request is made is not handled explicitly. So multiple dialogs were being shown when `launchMode=singleInstance` was absent due to some implicit handling by android. When the `launchMode` is present, it works as documented in Android documentation.

The good thing is that now that we know the exact cause, multiple solutions could be tried out. I will spend some time today to fix this. It should then work for your application without changing the `launchMode`.

**Comment by nishkarsh** [comment]
@mikejeep So the exact cause of the issue was at the place where the activity that contains permission dialog(s) was being started. 

Whenever a permission is requested, a `PermissionActivity` is started using `FLAG_ACTIVITY_NEW_TASK` flag. According to the documentation, while starting an activity with this flag, it searches for all existing tasks for an activity that has intent matching this intent and **_only_** if no matching activity is found is when a new task is created for new activity. However, if no `taskAffinity` is provided for this activity, it is not created in a new task, which was the case here.

When `launchMode=singleInstance` is provided, any new activity started from there has to start in a new task and that's where the actual documented behavior for `FLAG_ACTIVITY_NEW_TASK` is noticed. The intent for new permission activity remained same with just different `extras` due to which it brought back the same task in front without starting another activity.

An immediate solution for this is to make the intents different for different permission requests (different IntentAction would work) which is what I have done for now, but I have a few things in mind which I would implement soon to make this more stable (possibly without the need of starting new tasks).

**Comment by nishkarsh** [comment]
@mikejeep This should be fixed in version 0.1.7. Please upgrade the dependency to this version and it should work fine.
